// <auto-generated />
using System;
using ClicaMais.Infrastructure.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClicaMais.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ClicaMais.Domain.Models.Jogador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NivelAtualId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoAcumulado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoDeCliques")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NivelAtualId");

                    b.ToTable("Jogadores", (string)null);
                });

            modelBuilder.Entity("ClicaMais.Domain.Models.Nivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorMetaNivel")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorPorClique")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Niveis", (string)null);
                });

            modelBuilder.Entity("ClicaMais.Domain.Models.Saque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataProcessamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JogadorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorSolicitado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Saques", (string)null);
                });

            modelBuilder.Entity("ClicaMais.Domain.Models.Jogador", b =>
                {
                    b.HasOne("ClicaMais.Domain.Models.Nivel", "NivelAtual")
                        .WithMany()
                        .HasForeignKey("NivelAtualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelAtual");
                });
#pragma warning restore 612, 618
        }
    }
}
